version: '3'
services:
  frontend:
    build:
      context: ./next-frontend
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    ports:
      - "3000:3000"  # Maps container port 3000 to host port 3000
    depends_on:
      - backend
    networks:
      - janus_network

  backend:
    build: ./backend
    ports:
      - "8001:8001"  # Maps container port 8000 to host port 8001
    environment:
      - SUPABASE_URL=http://kong:8000  # Use Supabase's Kong service name
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
    networks:
      - janus_network

networks:
  janus_network:
    external: true